###
#TODO:
#MVN build (check)
#Spin up Tomcat(CHECK)
#Spin up postgres(CHECK)
#Add environment
#Add GeoServer
#Add depends_on
#Add Network
#ReverseProxy
###

version: '3.9'

services:
  db:
    image: docker.merkator.com/kargeo/postgis:1.0
    container_name: kargeo-postgis
    restart: always  
    environment:
      POSTGRES_PASSWORD: -@pass@-
    ports:
      - "127.0.0.1:5432:5432"
    networks:
        - kargeo-network
    volumes:
      - db_files:/var/lib/postgresql/data
  web:
    image: docker.merkator.com/kargeo/web:1.0.0.19
    restart: always
    container_name: kargeo-web
    depends_on:
        - "db"
    networks:
        - kargeo-network
  geoserver:
    restart: always
    image: docker.merkator.com/kargeo/geoserver:1.0
    container_name: kargeo-geoserver
    networks:
        - kargeo-network
    depends_on:
        - "db"
  kv7network:
    restart: always
    image: docker.merkator.com/kargeo/kv7network:1.0
    container_name: kargeo-kv7network
    networks:
        - kargeo-network
  proxy:
    image: docker.merkator.com/kargeo/proxy:1.0
    restart: always
    depends_on:
      - "web"
      - "kv7network"
      - "geoserver"
    container_name: kargeo-proxy
    networks:
      - kargeo-network    
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: docker.merkator.com/kargeo/certbot:1.0
    networks:
      - kargeo-network    
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  mail:
    image: docker.merkator.com/kargeo/smtp:1.0
    container_name: kargeo-mail
    restart: always
    networks:
        - kargeo-network
volumes:
  db_files:
    external: true

networks: 
  kargeo-network:
    driver: bridge
