###
#TODO:
#MVN build (check)
#Spin up Tomcat(CHECK)
#Spin up postgres(CHECK)
#Add environment
#Add GeoServer
#Add depends_on
#Add Network
#ReverseProxy
###

version: '3.9'

services:
  db:
    image: docker.merkator.com/kargeo/postgis
    container_name: kargeo-postgis
    restart: always
  
    environment:
      POSTGRES_PASSWORD: -@pass@-
    ports:
      - "5432:5432"
    networks:
        - kargeo-network
    volumes:
      - db_files:/var/lib/postgresql/data
  web:
    image: docker.merkator.com/kargeo/web
    container_name: kargeo-web
    ports:
      - "8080:8080"
    networks:
        - kargeo-network
  geoserver:
    image: docker.merkator.com/kargeo/geoserver
    container_name: kargeo-geoserver
    ports:
      - "8081:8080"
    networks:
        - kargeo-network
  kv7network:
    image: docker.merkator.com/kargeo/kv7network
    container_name: kargeo-kv7network
    ports:
      - "8082:8080"
    networks:
        - kargeo-network
  proxy:
    image: docker.merkator.com/kargeo/proxy
    restart: always
    container_name: kargeo-proxy
    networks:
      - kargeo-network    
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: docker.merkator.com/kargeo/certbot
    networks:
      - kargeo-network    
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  mail:
    image: docker.merkator.com/kargeo/smtp
    container_name: kargeo-mail
    restart: always
    networks:
        - kargeo-network
volumes:
  db_files:
    external: true

networks:
  kargeo-network:
    driver: bridge
